version: '3.4'

services:

  wordpress:
#    image: wordpress:latest
    build: wordpress
    restart: always
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./wordpress/data:/var/www/html/
    depends_on:
      - mysql
    environment:
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
